services:
    php:
        image: 'docker.io/library/php8.1-fpm-alpine'
        working_dir: /var/www/html
        volumes:
           - ./:/var/www/html
        command: php -S 0.0.0.0:8000 -t public